### PR TITLE
Provide comparable assertions for non comparable class when given a comparator

### LINKED ISSUE #1492: Provide comparable assertions for non comparable class when given a comparator
#### Summary

Comparable assertions are restricted to `Comparable` types, this could extended for non `Comparable` types if a proper `Comparator` is given.

This is issue was created after this discussion https://stackoverflow.com/questions/55811121/assertj-fluent-ordering-tests-with-custom-comparator/55828748?noredirect=1#comment98322628_55828748.

#### Example

```java
Foo foo1 = ...;
Foo foo2 = ...;
FooComparator fooComparator = ...;
assertThat(foo1).usingComparator(fooComparator).isGreaterThan(foo2);
```

We want to avoid  to copy comparable assertions in `AbstractAssert` as it would pollute the API.

The idea of this improvement is to return a `ComparableAssert` from `usingComparator` and then chain comparable assertions.  Moreover we would ideally keep the original type assertions.
Whether this is technically possible is something to explore as part of this improvement.

### PR DESCRIPTION
**Pull request by wettera**
#### Check List:
* Fixes #1492 
* Unit tests : YES
* Javadoc with a code example (on API only) : YES

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks, I will review your PR shortly !

**Comment by joel-costigliola** [comment]
The idea of this improvement was to return a `ComparableAssert` from `usingComparator` to avoid copying comparable assertions in `AbstractAssert`.

Whether this is technically possible is something to explore.

**Comment by wettera** [comment]
> @wettera sorry the issue was not properly described, the idea of this improvement was to return a `ComparableAssert` from `usingComparator` to avoid copying comparable assertions in `AbstractAssert`, if we did that we would expose `isLessThan` to all objects when it does not make sense for non comparable ones (the API would be polluted).
> 
> Whether this is technically possible is something to explore.

I get your idea, I will try it later

**Comment by joel-costigliola** [comment]
closed in favor of https://github.com/assertj/assertj-core/issues/2041

**Pull request closed without merging**
