### PR TITLE
Bnd 6.2.0

### PR DESCRIPTION
**Pull request by bjhargrave**
Update bnd maven plugins to 6.2.0 and move to use the new jar and test-jar goals of
bnd-maven-plugin.

Closes https://github.com/assertj/assertj-core/pull/2506

### CODE REVIEW

**Comment by bjhargrave** [comment]
cc: @rotty3000

**Comment by joel-costigliola** [comment]
thanks @bjhargrave!

**Comment by scordio** [comment]
@bjhargrave we have a [different configuration](https://github.com/assertj/assertj-guava/blob/541b47807205f3934db6687bfd966c3c54e542e5/pom.xml#L115-L134) in `assertj-guava` based on the `maven-bundle-plugin`. 

I guess we could use the `bnd-maven-plugin` instead, right?

**Comment by bjhargrave** [comment]
> I guess we could use the `bnd-maven-plugin` instead, right?

Yes, I'll make a PR.

**Pull request merged**
