### PR TITLE
GH-2639: Implement skeleton for ClassLoaderAssert

### PR DESCRIPTION
**Pull request by ascopes**
First PR for #2639.

- Implement skeleton type for AbstractClassLoaderAssert.
- Implement ClassLoaderAssert implementation.
- Hook up with Assertions, Assumptions, BDDAssertions, BDDAssumptions,
  BDDSoftAssertionsProvider, InstanceOfAssertFactories,
  StandardSoftAssertionsProvider, WithAssertions, and WithAssumptions.
- Write ClassLoaderAssert-bound tests for Assertions, Assumptions,
  BDDAssertions, BDDAssumptions, InstanceOfAssertFactories,
  WithAssertions.
- AssertionsUtil#expectAssumptionNotMetException now returns
  an AssumptionViolatedException rather than void, as to match with
  the API for AssertionsUtil#expectAssertionError. Since nothing
  relied on the return value before as this was a void method, this
  should not break anything existing.

I will add code examples to the second PR once a solid API has
been agreed on, as it prevents missing anything and creating
erroneous documentation.

### CODE REVIEW

**Comment by ascopes** [comment]
I am out for the rest of today and part of tomorrow, so I will likely continue to look at this on Sunday at some point

**Comment by scordio** [comment]
Sure, take your time @ascopes, and thank you!

**Comment by ascopes** [comment]
Added a commit at the start that addresses a transitive issue with the Future tests on the Windows runner. I will cherry-pick this onto a separate branch so it can be reviewed separately first.

**Comment by scordio** [comment]
Thanks @ascopes, I'll tackle this one as soon as I'm done with #2573

**Comment by scordio** [comment]
This is now merged. Thanks, @ascopes!

I applied some changes like adding the version tags and some missing `assertThat` entry points.

Also, I reverted the changes for `expectAssumptionNotMetException` - the idea is not wrong, but after some GIVEN / WHEN / THEN refactoring the change was no longer needed and I preferred to avoid another style of testing for assumptions, an area that is already quite heterogeneous.

**Pull request merged**
