### PR TITLE
Add scale assertions for BigDecimals.

### PR DESCRIPTION
**Pull request by talentedasian**
#### Check List:
* Fixes #??? (ignore if not applicable)
* Unit tests : YES 
* Javadoc with a code example (on API only) : YES 
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)
Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

### CODE REVIEW

**Comment by talentedasian** [comment]
This is kind of a [continuation to my previous PR](https://github.com/assertj/assertj-core/pull/2321#issuecomment-907902429) that added `hasScaleOf` assertion on BigDecimalAssert.

**Comment by talentedasian** [comment]
Not being impatient, it's been almost a month anyway. Any reviewer?

**Comment by joel-costigliola** [comment]
Fair enough, on it this week end! 😅

**Comment by joel-costigliola** [comment]
Integrated thanks @talentedasian!
Good PR, I added support for soft assertions which is a bit tricky to do (byte buddy magic under the hood)

**Pull request closed without merging**
