### PR TITLE
2570 adding to class assert

### LINKED ISSUE #2570: Add more assertion on ClassAssert
#### Summary

Apologies, If I'm wrong.

It's nice that the `ClassAssert` already has an assertion for [Class#isAssignableFrom](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#isAssignableFrom-java.lang.Class-).
An assertion of opposite flow may be more intuitive, I believe.
Say, we have the following class or any other class being expected to implement the `MyInterface` interface.

```java
class MyClass
        extends HisClass // which extends HerClass
        implements MyInterface {
}
```

```
HerClass
    HisClass
        MyClass
```

We can,

```java
// Asserts that MyInterface.class is assignable from MyClass.class, based on Class#isAssignableFrom
assertThat(MyInterface.class)
        .isAssignableFrom(MyClass.class);
// Asserts that MyClass.class has HisClass.class as direct superclass.
assertThat(MyClass.class)
        .hasSuperclass(HisClass.class);
```

But following idiom(s) will be more intuitive.

```java
// Asserts that MyClass implements MyInterface
assertThat(MyClass.class)
        .implements(MyInterface.class)
        .isAssignableTo(MyInterface.class);
// Or
assertThat(MyClass.class)
        .implements(MyInterface.class)
        .isSubclassOf(HisClass.class) // is direct subclass; opposite of hasSuperclass(superClass)
        .isDescendentOf(HisClass.class)
        .isDescendentOf(HerClass.class) // is direct or transitively
;
assertThat(HisClass.class)
        .isAscendentOf(MyClass.class)
        .isSubclassOf(HerClass.class)
        .isDescendentOf(HerClass.class);
```

- [ ] `isAssignableTo(classOrInterface)`
- [ ] `implements(interfaceClass)`
- [ ] `isSubclassOf(superClass)` - is direct subclass of
- [ ] `is(Descendant|Descendent)Of(ascendentClass)` - is direct or transitive descendent of
- [ ] `is(Ancestor|Ascendent)Of(descendentClass)` - is direct or transitive ascendent of

### PR DESCRIPTION
**Pull request by jessicant**
#### Check List:
* Fixes #2570
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

### CODE REVIEW

**Comment by nith2001** [comment]
Any updates for this? Just wanted to check in

**Comment by scordio** [comment]
Hi @nith2001, thank you for your patience. We are now focusing on releasing 3.23.0 and we will come back to new features once done with that.

**Comment by nith2001** [comment]
Any updates on this PR? Last I remembered, the tests were failing for alternate reasons.

**Comment by scordio** [comment]
@nith2001 once more, thanks for your patience!

The PR looks good and the failures are due to some flaky tests, nothing you need to worry about.

There are a few cosmetic changes I'd do like tests following the GIVEN/WHEN/THEN and # # the use of `expectAssertionError`, I'll take care of them during the merge which I try to get it done during the week.

**Comment by scordio** [comment]
Thanks, @jessicant and @nith2001!

A few changes I've applied:
* GIVEN/WHEN/THEN structure for tests.
* Assertion implementation moved to `AbstractClassAssert` as a private method, since it's unlikely it'll ever be shared with other internal parts of AssertJ. This simplifies the overall maintenance.

**Pull request merged**
