### PR TITLE
Feature/improve ci output

### PR DESCRIPTION
**Pull request by ascopes**
This contains several tweaks to the CI that make it a little easier to read, as well as adding functionality to add test result details as a comment to each PR. It also tweaks Jacoco so that local builds of forks/clones will opt into enabling Jacoco by default rather than having to explicitly run it.

- **Run mvnw in CI with batch flag** - this prevents some more noisy output from Maven that would otherwise make the logs more spammy.
- **Enable Jacoco on local builds by default** - CI then explicitly opts out of enabling this where important. This helps contributors be aware of the coverage as they make changes without having to remember to explicitly turn Jacoco on first.
- **Use Surefire v3, use JUnit5 reporters**:
    - Bump Surefire plugin to 3.0.0-M7, as this is stable despite being a prerelease, but contains numerous fixes and improvements compared to v2.22.x. These include fixes to potential crashes on some systems due to console log corruption, improved JUnit5 support, etc
    - Override default reporters for Surefire to use JUnit5 ones. This improves the format of the output logs in builds.
    - Prefer use of `@DisplayName` and `@ParameterizedTest` name for over the method name in Surefire reports, as this becomes easier to read and is prettier.
- <details>
    <summary>
      <strong>Report test results on PRs as a comment</strong> - this also adds some text to the Workflow page with the same details on it, and will automatically edit existing comments if results change or reruns occur. This requires two permissions to be set to <code>write</code> which I have added to that commit.
    </summary>
    
    
  </details>

- <details>
    <summary>
      <strong>Enable showing colour in GitHub action logs</strong> - this makes errors and warnings easier to spot, and makes the entire output a bit easier to read.
    </summary>
    
  </details>
  
- <details>
    <summary>
      <strong>Replace uninterpolated job name outside PRs</strong> - outside PRs, one of the job names was explicitly showing up with a mangled name due to a context variable being missing. This just fixes that:
    </summary>
    
  </details>

### CODE REVIEW

**Comment by ascopes** [comment]
As a side note, for the `null`-named tests in the Surefire output, I have opened [SUREFIRE-2101](https://issues.apache.org/jira/browse/SUREFIRE-2101) on the Apache Foundation JIRA, and submitted https://github.com/apache/maven-surefire/pull/549 as a potential patch for this.

**Comment by vlsi** [comment]
Thanks for improving CI output.
The current log output is indeed cluttered, and it impacts contributors' experience.

> prevents some more noisy output from Maven that would otherwise make the logs more spammy.

It would be nice if Maven could be configured to skip printing 10'000+ log lines for a successful build. Is there a real need to print each and every test class (method) twice?

```
[INFO] Running AnyElementsShouldMatch create
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in AnyElementsShouldMatch create
```

Is there a way to remove noise from javadoc?

```
[WARNING] Generating /home/runner/work/assertj-core/assertj-core/target/site/apidocs/org/assertj/core/api/junit/jupiter/SoftAssertionsExtension.html...
[WARNING] Generating /home/runner/work/assertj-core/assertj-core/target/site/apidocs/org/assertj/core/api/SoftAssertionsProvider.html...
[WARNING] Generating /home/runner/work/assertj-core/assertj-core/target/site/apidocs/org/assertj/core/api/SoftAssertionsProvider.ThrowingRunnable.html...
[WARNING] Generating /home/runner/work/assertj-core/assertj-core/target/site/apidocs/org/assertj/core/api/SoftAssertionsRule.html...
```

**Comment by ascopes** [comment]
> Is there a way to remove noise from javadoc?

Not that I know of currently, @vlsi. It may be easier to move javadoc to a separate step that can run in parallel. It wouldn't stop the noise, but it would keep it separate.

I have a similar issue in one of my builds I think, where as soon as Javadoc enounters a single warning, it reports everything under that same level by the looks. 

I will have a think and see if I can find anything!

**Comment by ascopes** [comment]
Thinking about this further, maybe it is worth having a component in a separate repo to configure this reporting? It would then be able to be used consistently across all assertj repos using the parent POM.

**Comment by ascopes** [comment]
Latest build failure is relating to https://github.com/EnricoMi/publish-unit-test-result-action/issues/307, will update if needed.

**Comment by joel-costigliola** [comment]
thanks @ascopes, let's see how it goes.

**Review by Li900j — COMMENTED** [review]
.github/workflows/binary-compatibility.yml

**Pull request merged**
