### PR TITLE
Add IgnoringCase variants of startsWith and endsWith (#2449)

### LINKED ISSUE #2449: Add `startsWithIgnoringCase` and `endsWithIgnoringCase` to AbstractCharSequenceAssert
#### Summary
While migrating assertions from Hamcrest to AssertJ I noticed there was no AssertJ equivalent to Hamcrest's `org.hamcrest.Matchers#startsWithIgnoringCase` and `org.hamcrest.Matchers#endsWithIgnoringCase`. However, AssertJ does provide `org.assertj.core.api.AbstractCharSequenceAssert#containsIgnoringCase` which is equivalent to Hamcrest's `org.hamcrest.Matchers#containsStringIgnoringCase`, so there is precedence in providing "ignoringCase" alternatives.

#### Example

```java
// assertion will pass
assertThat("Gandalf the grey").startsWithIgnoringCase("Gandalf");
assertThat("Gandalf the grey").startsWithIgnoringCase("gandalf");

//assertions will fail
assertThat("Gandalf the grey").startsWithIgnoringCase("grey");
```

and

```java
// assertion will pass
assertThat("Gandalf the grey").endsWithIgnoringCase("grey");
assertThat("Gandalf the grey").endsWithIgnoringCase("Grey");

//assertions will fail
assertThat("Gandalf the grey").endsWithIgnoringCase("Gandalf");
```

If you agree that this would be a reasonable addition to the API, I would be happy to take first stab at implementing this.

### PR DESCRIPTION
**Pull request by bbogason**
Add startsWithIgnoringCase, endsWithIgnoringCase, doesNotStartWithIgnoringCase, and doesNotEndWithIgnoringCase on AbstractCharSequenceAssert (#2449)

#### Check List:
* Fixes #2449 
* Unit tests : YES
* Javadoc with a code example (on API only) : YES
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by bbogason** [comment]
> [scordio](/scordio) added this to the [3.23.0](/assertj/assertj-core/milestone/63) milestone [3 days ago](#event-5819375933)

@scordio Let me know if you want me to update the `@since` tags, I had initially put `@since 3.22.0` on everything.

Also let me know if there is something I should do to fix the 2 failing checks.

**Comment by scordio** [comment]
Thank you, @bbogason.

About the failing checks:
* The binary compatibility fails because your branch is not up to date with `main`, a rebase should fix it.
* pitest has a well-known issue, nothing you need to worry about.

About the version numbers, no action is needed at the moment: we are finalizing the release of 3.22.0 but we might include some more features like yours. If an update is necessary, we'll do it during the merge.

**Comment by DiegoKrupitza** [comment]
Is there an update on this PR, since this new feature is quite helpful for a project I am currently working on and the "workaround" is quite ugly.

**Comment by scordio** [comment]
This will be part of 3.23.0. As we recently released 3.22.0, it will take some time for the next version to be ready.

**Comment by DiegoKrupitza** [comment]
> This will be part of 3.23.0. As we recently released 3.22.0, it will take some time for the next version to be ready.

Thank you! :)

**Comment by joel-costigliola** [comment]
Integrated thanks @bbogason!

**Pull request closed without merging**
