### PR TITLE
#2132 Wrong error message in assertion when using Set collection

### LINKED ISSUE #2132: Wrong collection type in Set assertion
#### Summary

The assertion error displays the wrong collection type, as noticed by @Patouche.

#### Example

```java
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

class AssertJTests {

    @Test
    void iterable_bad_name() {
        final Set<String> actual = Stream.of("toto", "tata").collect(Collectors.toSet());
        Assertions.assertThat(actual).contains("tutu");
    }
}
```

The error is as follows:
```java
java.lang.AssertionError: 
Expecting ArrayList:
 <["toto", "tata"]>
to contain:
 <["tutu"]>
but could not find the following element(s):
 <["tutu"]>
```

`ArrayList` should not be displayed in the error message.

### PR DESCRIPTION
**Pull request by Patouche**
#### Check List:
* Fixes #2132 
* Unit tests : YES 
* Javadoc with a code example (on API only) : NA

### CODE REVIEW

**Review by scordio — APPROVED** [review]
Minor: `then()` could be favored instead of `assertThat()`

**Comment by Patouche** [comment]
I took all your remarks into accounts and rebase on top of main.

Should I squash also my 3 commits or is it good for you ?

**Comment by scordio** [comment]
Merged, thanks @Patouche!

**Comment by joel-costigliola** [comment]
thanks @Patouche, no need to squash the PRs are set to be squashed and rebased

**Pull request merged**
