### PR TITLE
Add `linesOf` variants for a `Path` content

### LINKED ISSUE #2617: `linesOf` variants for `Path` content
`Path` related variants of [`linesOf`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assertions.html#linesOf(java.io.File)) are currently not available.

### PR DESCRIPTION
**Pull request by StefanBratanov**
#### Check List:
* Fixes #2617 
* Unit tests : YES
* Javadoc with a code example (on API only) : NA
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

`BDDAssertions` uses `@since` in the javadoc, but wasn't sure which version to add

### CODE REVIEW

**Comment by scordio** [comment]
Thanks for the fast turnaround, @StefanBratanov!

> `BDDAssertions` uses `@since` in the javadoc, but wasn't sure which version to add

We're now focusing on finalizing 3.23.0, let's see if we can squeeze this in. Please use 3.23.0.

**Comment by StefanBratanov** [comment]
> Thanks for the fast turnaround, @StefanBratanov!
> 
> > `BDDAssertions` uses `@since` in the javadoc, but wasn't sure which version to add
> 
> We're now focusing on finalizing 3.23.0, let's see if we can squeeze this PR in the release. Please use 3.23.0.

Thank you. :) Done.

**Comment by scordio** [comment]
Thanks for your first contribution, @StefanBratanov!

**Comment by StefanBratanov** [comment]
> Thanks for your first contribution, @StefanBratanov!

No worries :) I have been using AssertJ for a long time and it's great to have a chance to look at the underlying code and make changes. Thank you for making it easy to contribute.

**Pull request merged**
