### PR TITLE
The white space was deleted in shouldNotBe and the format was changed…

### LINKED ISSUE #2202: ShouldNotBe: missing linebreak OR to much whitespaces
ShouldNotBe has a missing linebreak OR to much whitespaces.

https://github.com/assertj/assertj-core/blob/e14081576c22240c45dd2f8f2d3afa7d42303faf/src/main/java/org/assertj/core/error/ShouldNotBe.java#L38

`"%nExpecting actual:%n  %s%nnot to be [ ]%s"`

### PR DESCRIPTION
**Pull request by Annette0127**
… in shouldNotHave.

#### Check List:
* Fixes #2202 
* Unit tests : NO
* Javadoc with a code example (on API only) : NO
* PR meets the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md)

Following the [contributing guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md) will make it easier for us to review and accept your PR.

### CODE REVIEW

**Comment by stbischof** [comment]
There are also relating Tests
Like:

https://github.com/assertj/assertj-core/blob/0b6d61a7018f8f8f2f06991a11aeeca5ac4377ea/src/test/java/org/assertj/core/error/ShouldNotBe_create_Test.java

**Comment by Annette0127** [comment]
@stbischof Oh, thank you very much for this!

**Comment by Annette0127** [comment]
I have checked all tests again and found except two test cases (`should_ignore_test_when_one_of_the_assumption_fails` in `assertj-core/src/test/java/org/assertj/core/osgi/AssumptionsTest.java` and `verify_classloaders` in `assertj-core/src/test/java/org/assertj/core/osgi/soft/CustomSoftAssertionTest.java`) failed, others all passed. And these two failed are not because of the modification here. : )

**Comment by joel-costigliola** [comment]
Integrated thanks @Annette0127!

**Pull request merged**
